# overprovisioned-secrets.yml
#
# what: workflows that inject the entire secrets context into the runner
# violate the principle of least authority since the runner
# can access all secrets, not just the ones it needs.
#
# how: injecting the entire secrets context into the runner instead of
# selectively injecting only the necessary secrets.

on: push

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${stuff} ${otherstuff} ${morestuff}"
        env:
          # NOT OK: injects the entire secrets context into the runner
          stuff: ${{ format('{0}', toJSON(secrets)) }}
          # OK: selectively injects a single secret
          otherstuff: ${{ secrets.otherstuff }}
          # OK: weird, but still selectively injects only a single secret
          morestuff: ${{ toJSON(secrets.morestuff) }}

      - run: |
          some-random-command <<< "${secrets_json}"
        env:
          # NOT OK: injects the entire secrets context into the runner
          secrets_json: ${{ toJSON(secrets) }}
