# secrets-inherit.yml
#
# what:
# calls reusable workflows with `secrets: inherit`. this shares all secrets
# with the reusable workflow instead of limiting its access to just the secrets
# it needs, violating POLA.
#
#
# how:
# user error.

on: push

permissions: {}

jobs:
  call-workflow-vulnerable-1:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    # NOT OK: unconditionally inherits
    secrets: inherit

  call-workflow-not-vulnerable-2:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    # OK: explicitly forwards intended secrets
    secrets:
      special-secret: ${{ secrets.special-secret }}

  call-workflow-not-vulnerable-3:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    # OK: no secrets forwarded

  call-workflow-not-vulnerable-4:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    # OK: no secrets forwarded
    secrets: {}
