# unredacted-secrets.yml
#
# what: use of structured secrets that are then decoded can lead to
# unredacted secrets in the runner's logs.
#
# how: accessing structured secrets by field instead of decomposing
# each field into its own secret variable.

on: push

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${stuff} ${otherstuff}"
        env:
          # NOT OK: potentially leaves 'password' unredacted in the runner's logs
          stuff: ${{ fromJSON(secrets.password) }}

          # NOT OK: potentially leaves 'field' within 'otherstuff' unredacted in the runner's logs
          otherstuff: ${{ fromJson(secrets.otherstuff).field }}

